#!/usr/bin/env python
 
import sys
import urllib
import urllib2

from bs4 import BeautifulSoup
from datetime import date

if sys.argv.__len__() == 4:

	def main():
           response = make_request()
           table = parse_doc(response) 
           data = compose_required_range(table.find_all('tr')[1:-2])
           total = sum(map(lambda d:int(d) ,data.values()))
           print "Between " + sys.argv[2] +" and "+ sys.argv[3] +" the total number of male children named "+sys.argv[1]+" was "+ str(total)

	def number_of_years():
	    return (date.today().year - 1) - 1879

        def compose_required_range(trs):
	   rows = {}
	   for row in trs:
               cells = row.find_all('td')
               rows[cells[0].string.encode('utf-8')] = cells[1].string.encode('utf-8')
           return time_range(rows, int(sys.argv[2]), int(sys.argv[3]))


        def time_range(data, start, end):
           results = []
           for year,rank in data.items():
               if int(year) in range(start+1, end+1):
 	          results.append((year,rank))
           return dict(results)

        def make_request():
 	   data = urllib.urlencode({'name': sys.argv[1], 'nyrs': number_of_years(), 'sex':'N'})
           response = urllib2.urlopen('http://www.socialsecurity.gov/cgi-bin/babyname.cgi', data)
           return response.read()

	def parse_doc(resp):
	   doc_tree = BeautifulSoup(resp) 
           return doc_tree.find('table', width='60%')   	   
        
	main()

else:

	print 'Error: Check your arguments. Example: ./babyStat [name] [start year] [end year]'
