#!/usr/bin/env python
 
import sys
import urllib
import urllib2

from bs4 import BeautifulSoup
from datetime import date

if sys.argv.__len__() == 4:

	def main():
		data = urllib.urlencode({'name': sys.argv[1], 'nyrs': derive_number_of_years(), 'sex':'N'})
		response = urllib2.urlopen('http://www.socialsecurity.gov/cgi-bin/babyname.cgi', data)

		doc_tree = BeautifulSoup(response.read()) 
		print doc_tree('table', width='60%')

	def derive_number_of_years():
	    return (date.today().year - 1) - 1879


	main()

else:
	print 'Error: Check your number of arguments'
